apiVersion: v1
kind: Pod
metadata:
    name: systemctl-test
    namespace: crowsnest
    labels:
      app.kubernetes.io/name: systemctl-test
      app.kubernetes.io/part-of: crowsnest
spec:
    serviceAccountName: crowsnest
    containers:
      - name: systemctl
        image: registry.access.redhat.com/ubi9/ubi:9.7
        command: ["/bin/sh", "-c", "while :; do sleep 5; done"]
        securityContext:
          privileged: false
          #allowPrivilegeEscalation: false
          runAsUser: 100
          capabilities:
            add:
            - CAP_SYS_BOOT
        volumeMounts:
          - name: run-systemd-system
            mountPath: /run/systemd/system
            readOnly: true
          - name: var-run-dbus
            mountPath: /var/run/dbus
            readOnly: true
          - name: sys-fs-cgroup
            mountPath: /sys/fs/cgroup
            readOnly: true          
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
    volumes:
    - name: run-systemd-system
      hostPath:
        path: /run/systemd/system
        type: Directory
    - name: var-run-dbus
      hostPath:
        path: /var/run/dbus
        type: Directory
    - name: sys-fs-cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory

